name: AWS Code Deploy

on:
  push:
    branches: [ main ]
jobs:
  listS3:
    runs-on: ubuntu-latest
    steps:
      - name: Run AWS CodeDeploy
      - uses: chrislennon/action-aws-cli@v1.1
        run: git pull
        with:
          args: deploy create-deployment --application-name "CodeDeployDemoApp" --deployment-group-name "AutoDeployDemoGroup" --github-location repository="TakatokiOshima/code-deploy-demo",commitId="${{ github.sha }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-northeast-1"
